### ISSUE TITLE
Discord link expired & model support

### ISSUE THREAD

**Issue by cmsj** [toremick/shorai-esp32#13]
I was going to swing by the Discord to ask some questions, but the invite link seems to have expired.

My main question is about supporting other models of Toshiba ACs - specifically, I have a Mirai RAS-18BKVG-E and I can't find any information online about which of the several official WiFi adapters it should be using, but I'm guessing they have a pretty similar communication protocol to the Shorai models.
I'm curious if anyone knows about whether that's true, or even how I would find out which official WiFi adapter I should use, so I can see if it's the same one that works with Shorai and therefore this project should work for me.

**Comment by toremick** [comment]
Hi cmsj, have updated the discord invite now.
About other models i honestly cant tell much, but maybe someone on discord have tested.

found this:
https://www.orionairsales.co.uk/toshiba-air-conditioning-wall-mounted-mirai-ras-b18bkvg-e-5kw18000btu-r32-a-heat-pump-240v50hz-14129-p.asp

looks like your model uses the RB-N102S-G, which is the same as the shorai uses, so i GUESS this will work with your unit too.

**Comment by cmsj** [comment]
Closing because IntEx on Discord analysed the service manual for my model and confirmed there is no wifi module interface. Thanks for the help anyway!
