### ISSUE TITLE
Question about connecting to an air conditioner 

### ISSUE THREAD

**Issue by techmike78** [toremick/shorai-esp32#6]
Good day.

Please tell me which connector to connect your device to? I have two connectors on the RAS-07J2KVG-EE, one is on the controller board (dad), the second is already with the cable (mom).
Which one to connect to?
![изображение](https://user-images.githubusercontent.com/47521414/125751701-2b6875e9-bfdf-4793-85b9-18f75df7ad94.png)

**Comment by toremick** [comment]
Number 2 is the correct one.  (In fact number 2 is just a extension cable connected to number 1)

**Comment by techmike78** [comment]
Thanks for the quick response.
Are optocouplers required or are they for reliability?

**Comment by toremick** [comment]
> Thanks for the quick response.
> Are optocouplers required or are they for reliability?

They are used for level converting. Have heard of others using different kind of level shifters, but this is the same way the original gateway does it.

**Comment by techmike78** [comment]
Have you disassembled and copied the diagram of the original RB-N104S-G or RB-N103S-G block?
Where can I find it, I'm wondering how the rest is done there, maybe it is possible to simplify the alignment of the levels?

**Comment by toremick** [comment]
No, just followed the trace.

**Comment by techmike78** [comment]
Are you planning to upload the firmware sources?
Is HA discovering currently supported?

**Comment by toremick** [comment]
The firmware is basically a original micropython firmware  with a script embedded. The script is a tweak of the ota_updater.py to be used as a installer.
HA discovering is not currently supported, but should be i guess.

**Comment by techmike78** [comment]
C micropython did not work, it is interesting to see what protocol the air conditioner has.

Thanks for the help.

**Comment by techmike78** [comment]
The optocoupler can be PC817, it doesn't matter how to use PC871A in the sheme?

**Comment by toremick** [comment]
Have not tried the different optocouplers, but guess they can be interchangeable, its easier and faster to take these questions in the discord btw.
